### ISSUE TITLE
Error "Failed to issue query, error message : MDB2 Error: unknown error"

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips-cp#10]
Good day! I found problem in Users -> User Management.
![error_screen](https://user-images.githubusercontent.com/3471049/27471229-c7b7a658-57ff-11e7-96e1-67072faf19d3.png)

opensips-cp makes a request to postgres:
```
select count(*) from subscriber s  order by s.id asc
```

In logs i see:
```
Jun 23 07:21:14 144153 postgres[7132]: [5-1] < 2017-06-23 07:21:14.967 UTC >ERROR:  column "s.id" must appear in the GROUP BY clause or be used in an aggregate function at character 45
Jun 23 07:21:14 144153 postgres[7132]: [5-2] < 2017-06-23 07:21:14.967 UTC >STATEMENT:  select count(*) from subscriber s  order by s.id asc
```
Attach the pcap file with packets(Frame 16 is bad request):
[bad_request.pcap.zip](https://github.com/OpenSIPS/opensips-cp/files/1097081/bad_request.pcap.zip)

In postgres table i have:
```
opensips=# select * from domain;
 id |    domain     | attrs |       last_modified        
----+---------------+-------+----------------------------
  1 | 89.223.25.188 |       | 2017-05-23 11:41:33.813304

```

**Comment by bogdan-iancu** [comment]
@kertor , as I do not have postgres with OpenSIPS, could you please run in the postgres client:
  select count(*) from subscriber s  order by s.id asc
and
  select count(*) from subscriber order by id asc

Thanks,
Bogdan

**Comment by kertor** [comment]
Yes. This examples:
Errors:
```
opensips=> select count(*) from subscriber s order by s.id asc;
ERROR:  column "s.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select count(*) from subscriber s order by s.id asc;
```

```
opensips=> select count() from subscriber order by id asc;
ERROR:  count(*) must be used to call a parameterless aggregate function
LINE 1: select count() from subscriber order by id asc;
```
```
opensips=> select count(*) from subscriber order by id asc;
ERROR:  column "subscriber.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select count(*) from subscriber order by id asc;
```

Correct examples:
```
opensips=> select count(*) from subscriber group by id ;
 count 
-------
     1
     1
     1
     1
     1
(5 lines)
```
```
opensips=> select count(*) from subscriber;
 count 
-------
     5
```

**Comment by bogdan-iancu** [comment]
@kertor , please see 5280d88 - I removed the "order by" and "asc" when doing "count(*)" as it makes no sense (as logic) - I hope this makes postgres also happy :) . Let me know.

**Comment by kertor** [comment]
It`s ok, but now i see "No data found":
![empty_screen2](https://user-images.githubusercontent.com/3471049/27485676-5790c9cc-5836-11e7-8053-66c8d8ba7d3b.png)

In dump data all correct:
[dump2.pcap.zip](https://github.com/OpenSIPS/opensips-cp/files/1098010/dump2.pcap.zip)

Similar error in "Users->ACL Management":
![error_screen2](https://user-images.githubusercontent.com/3471049/27485891-561f7754-5837-11e7-8717-fcdc77967db6.png)

```
Jun 23 12:53:47 144153 postgres[8645]: [5-1] < 2017-06-23 12:53:47.670 UTC >ERROR:  column "dbaliases.id" must appear in the GROUP BY clause or be used in an aggregate function at character 130
Jun 23 12:53:47 144153 postgres[8645]: [5-2] < 2017-06-23 12:53:47.670 UTC >STATEMENT:  select count(*) from dbaliases where (1=1)  and username like '%' and alias_username like '%' and alias_domain like '%' order by id asc
```

I am test this case:
Correct:
```
opensips=> select count(*) from dbaliases where (1=1)  and username like '%' and alias_username like '%' and alias_domain like '%' group by id;
 count 
-------
(0 lines)
```

**Comment by bogdan-iancu** [comment]
@kertor , for the User Management issue,  please add after the existing line 199 (https://github.com/OpenSIPS/opensips-cp/blob/6.2/web/tools/users/user_management/template/user_management.main.php#L199)  this new line:
`print_r($resultset);`

and paste here the extra output will get in the User Management tool, right on top of the table listing the users.

In the mean while, I will check the Aliases part.

Thanks, Bogdan

**Comment by bogdan-iancu** [comment]
@kertor , for the Aliases Management, see this fix be2ee93dbe738faa81c87f7f9c2868f438da82cb for CP 6.2 . Hopefully it will solve the SQL syntax errors in postgres.

**Comment by bogdan-iancu** [comment]
@kertor , I ran multiple tests over a postgres DB and fixed several issues  - on the 6.3 branch see 73ff6dd1c23dd37f91b8057ac3ff86475a0759ae and a246b9798e634bd691aa16bc16b64b0a6c16750b .
Let me know if it works for you now.

**Comment by kertor** [comment]
Hello Bogdan! I check opensips-cp after your update repo.
Almost everything works correctly, I do not see old problems.
But i see **first problem** here: System->CDR Viewer. 
Error text on page: 
```
Failed to issue query, error message : MDB2 Error: unknown error
```
Error in pgsql logs:
```
Jun 29 09:20:44 144153 postgres[5424]: [5-2] < 2017-06-29 09:20:44.714 UTC >HINT:  Use separate LIMIT and OFFSET clauses.
Jun 29 09:20:44 144153 postgres[5424]: [5-3] < 2017-06-29 09:20:44.714 UTC >STATEMENT:  select *  from acc where (1=1)  order by time desc  LIMIT 0, 30
```

**Second problem:**
Then i tryng add new Alias over opensips-cp i see this error in pgsql logs:
```
Jun 29 09:26:53 144153 postgres[5464]: [5-1] < 2017-06-29 09:26:53.872 UTC >ERROR:  syntax error at or near "(" at character 46
Jun 29 09:26:53 144153 postgres[5464]: [5-2] < 2017-06-29 09:26:53.872 UTC >STATEMENT:  INSERT INTO
Jun 29 09:26:53 144153 postgres[5464]: [5-3] #011                                (alias_username, alias_domain, username, domain) VALUES
Jun 29 09:26:53 144153 postgres[5464]: [5-4] #011                                ('8000','ANY','7000','89.223.25.188')
```

**The third problem.** 
Then i trying to add new Cluster in System->Clusterer i see this error in pgsql logs:
```
Jun 29 09:31:34 144153 postgres[5493]: [5-1] < 2017-06-29 09:31:34.465 UTC >ERROR:  column "machine_id" does not exist at character 48
Jun 29 09:31:34 144153 postgres[5493]: [5-2] < 2017-06-29 09:31:34.465 UTC >STATEMENT:  SELECT * FROM clusterer WHERE cluster_id=2 and machine_id=2
```

in /usr/share/opensips/postgres/cat clusterer-create.sql i see:
```
INSERT INTO version (table_name, table_version) values ('clusterer','2');
CREATE TABLE clusterer (
    id SERIAL PRIMARY KEY NOT NULL,
    cluster_id INTEGER NOT NULL,
    node_id INTEGER NOT NULL,
    url VARCHAR(64) NOT NULL,
    state INTEGER DEFAULT 1 NOT NULL,
    ls_seq_no INTEGER DEFAULT 0 NOT NULL,
    top_seq_no INTEGER DEFAULT 0 NOT NULL,
    no_ping_retries INTEGER DEFAULT 3 NOT NULL,
    priority INTEGER DEFAULT 50 NOT NULL,
    sip_addr VARCHAR(64),
    description VARCHAR(64),
    CONSTRAINT clusterer_clusterer_idx UNIQUE (cluster_id, node_id)
);
```
machine_id is missing. I think,  maybe i must update opensips - i try that.

**Comment by bogdan-iancu** [comment]
Hi @kertor , the first issue should be fixed by the above commits ( c1bbf9f on trunk , 0860788 on 6.2 ).

For the item 3, you are using the DB schema from OpenSIPS 2.3 with CP 6.2 (which is for OpenSIPS 2.2).

**Comment by bogdan-iancu** [comment]
OK, regarding the second problem - you probably used "ANY" option for the "Alias Type" when creating the alias - this lead to a bogus table name (this is why the DB query failed).
Anyhow, I pushed a fix to remove the ANY option when doing Add/Edit operations (to force you to select a real domain or alias type). Still the ANY is kept as wildcard when doing search.
Pull the above fixes and give it a try.

**Comment by ketan-kothari** [comment]
Hello Bogdan,

I'm using opensips 2.3.1 with cp 7.2.
getting Failed to issue query, error message : MDB2 Error: unknown error of sip trace module also getting Error code 500 (Command not found) in MI Command

![oscp2](https://user-images.githubusercontent.com/30174460/31008500-fa3ea9e0-a521-11e7-937b-bc07b62d22e5.png)
![oscp1](https://user-images.githubusercontent.com/30174460/31008504-fdc3dfb8-a521-11e7-9a16-e93b0cb1841c.png)

**Comment by bogdan-iancu** [comment]
@ketan-kothari , please open a new ticket for your report as it is not related to the original report here.
