### ISSUE TITLE
[Setting] migrate all tools to new settings engine

### ISSUE THREAD

**Issue by bogdan-iancu** [OpenSIPS/opensips-cp#135]
First step is to evaluate the list of tools still using the local.inc.php, so we can put together a plan to migrate them to the new settings engine.

**Comment by airineidaniel23** [comment]
Tools that are not yet migrated:

- [ ] callcenter
- [ ] cdrviewer
- [ ] tviewer
- [ ] siptrace
- [ ] monit
- [ ] mi
