### ISSUE TITLE
Failed to issue query, error message : MDB2 Error: unknown error

### ISSUE THREAD

**Issue by ketan-kothari** [OpenSIPS/opensips-cp#14]
Hello Bogdan,

I'm using opensips 2.3.1 with cp 7.2.
getting Failed to issue query, error message : MDB2 Error: unknown error of sip trace module also getting Error code 500 (Command not found) in MI Command

![oscp2](https://user-images.githubusercontent.com/30174460/31008500-fa3ea9e0-a521-11e7-937b-bc07b62d22e5.png)
![oscp1](https://user-images.githubusercontent.com/30174460/31008504-fdc3dfb8-a521-11e7-9a16-e93b0cb1841c.png)

**Comment by bogdan-iancu** [comment]
@ketan-kothari , as per IRC discussion, this was a setting issue and it was fixed, so I will close this.
