### ISSUE TITLE
incorrect variable suffixes in opensips-cp/config/tools/users/acl_management/db.inc.php

### ISSUE THREAD

**Issue by barbarello** [OpenSIPS/opensips-cp#15]
Hi @bogdan-iancu 

Is it possible that the variables in opensips-cp/config/tools/users/acl_management/db.inc.php were meant to be suffixed 'acl_management'  rather than 'alias_management'  ?

Just curious why the naming is not consistent with the rest of the modules

Thank you.

**Comment by bogdan-iancu** [comment]
Hi @barbarello, that is actually a bug ! Thanks for spotting it, I will shortly fix it.

**Comment by bogdan-iancu** [comment]
Done, thanks again for the report
