### ISSUE TITLE
drouting: "MDB2 Error: no such field" when searching for gateway ip address

### ISSUE THREAD

**Issue by MaxMuehlbronner** [OpenSIPS/opensips-cp#2]
https://github.com/OpenSIPS/opensips-cp/blob/master/web/tools/system/drouting/template/gateways.main.php#L174

When searching for a specific gateway IP the error message is : mdb2 - no such field. When printing out the sql query it revealed that the query result is ordered by "ruleid" ?

But the gateways table does not have a ruleid at all.  When removing the order by from line 174 the gateway search works just fine, but i am wondering whether this is a bug or it has another reason?

**Comment by razvancrainea** [comment]
The `order by` is used to make sure you get the gateways in the same order as without a filter.
However, most likely there is a copy&paste error from the rules tab. I will push a fix shortly.
