### ISSUE TITLE
Mispelled table domains

### ISSUE THREAD

**Issue by flaviogoncalves** [OpenSIPS/opensips-cp#204]
I was installing the new OpenSIPS Control Panel 9.3.2 and I found the file /var/www/html/opensips-cp/config/tools/system/domains/settings.inc.phg with the table_name "domains". I was having errors for the table not found. 

"table_domains" => array(
		"default" => "domains",
		"name" => "Table Domains",
		"type" => "text",
		"validation_regex" => $table_regex,
		"tip"  => "The database table name for storing the domain entries"
	),

The correct is "domain". I changed to domain and started working just fine.

**Comment by bogdan-iancu** [comment]
Fixed via 203709f087c9c8a93bdb08c4b121798bef809c36
