### ISSUE TITLE
Opensips CP 8.3.2 has limited reload operation in tviewer module

### ISSUE THREAD

**Issue by Integration-IT** [OpenSIPS/opensips-cp#208]
Opensips CP 8.3.2 has limited reload operation in tviewer module, i suppose it can not handle commands with arguments and parameters.
CLI:
```
(cli): mi rc_reloadClientRate name=my_client rateid=1 wholesale=1
"OK"
(cli): mi rc_reloadClientRate my_client 1 1
"OK"
```

LOCAL.INC.PHP (FAIL):
` $custom_config[$module_id][0]['custom_mi_command'] = "rc_reloadClientRate name=my_client rateid=1 wholesale=1";`

LOG:
`ERROR:core:handle_mi_request: Command not found`

LOCAL.INC.PHP (FAIL):
` $custom_config[$module_id][0]['custom_mi_command'] = "rc_reloadClientRate my_client 1 1";`

LOG:
`ERROR:core:handle_mi_request: Command not found`

LOCAL.INC.PHP no param (WORKED):
` $custom_config[$module_id][0]['custom_mi_command'] = "dp_reload";`

LOG:
```
INFO:db_mysql:switch_state_to_disconnected: disconnect event for ...
INFO:db_mysql:reset_all_statements: resetting all statements on connection: ...
INFO:db_mysql:connect_with_retry: re-connected successful for ...
```

**Comment by brettnem** [comment]
I am also having this exact same problem.
