### ISSUE TITLE
Cannot specify transport type in Control Panel for Dispatcher

### ISSUE THREAD

**Issue by AustinLangston** [OpenSIPS/opensips-cp#281]
When attempting to add a new destination which uses TCP or TLS I cannot set the value within the dispatcher table. I can add it to the Database for OpenSIPS and it will work, but I cannot use the control panel.
![image](https://github.com/OpenSIPS/opensips-cp/assets/102175750/01f183e6-327a-481e-b33a-552af3369960)

I did open up a PR to fix this as well; it may be missing other protocols though as I only included TCP, TLS, and UDP.
https://github.com/OpenSIPS/opensips-cp/pull/280

**Comment by bogdan-iancu** [comment]
closing as the PR was merged
