### ISSUE TITLE
Control Panel 9.3.3 - Dynamic Routing Module - GW Type change is not saved on db

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips-cp#282]
Dear Team,

I am using Control Panel 9.3.3

On Dynamic Routing module --> on https://X.X.X.X/cp/tools/system/drouting/gateways.php when you edit 
a Gateway and change the "GW Type" this change is not saved on db and it keeps the previous value.

Thank you in advance
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Just a small note that I have just noticed. 
This is not working when "Attributes" field has value. 
When "Attributes" is empty the "GW Type" change is saved correctly on the db.

**Comment by Integration-IT** [comment]
Hi @vtzan , @airineidaniel23 

All is fine if I add one.
I have the same issue if I modify one only.

This is related to this line 138 : [$type = get_settings_value("default_gw_type");](https://github.com/OpenSIPS/opensips-cp/blob/675e558e4fdb45d4df15db713a56bbaefada1ada/web/tools/system/drouting/gateways.php#L138C31-L138C46)

whatever you put inside, when you want save, the type is set to the default gw type from "Settings for Dynamic Routing", section "Default gateway type".

**Comment by razvancrainea** [comment]
Thank you for your report, this seems to have been a merging issue. I am going to push a fix right away.
