### ISSUE TITLE
Sending to json:127.0.0.1:8888/mi : MI command failed with code -32601 (Method not found)

### ISSUE THREAD

**Issue by E2-Sterlin** [OpenSIPS/opensips-cp#290]
I have configured Opensips 9.3.4  and Opensips-cp 9.3.4.

While adding the domain and clicking on reloading server, I am getting the error mentioned below

![image](https://github.com/OpenSIPS/opensips-cp/assets/120548459/7e927f44-f697-43e0-826b-9eda33da6c53)

Kindly help me regarding this.

Thanks in advance

**Comment by Erwindae59** [comment]
Hello, 

Fresh install too, and same troubles in various pages : 
![image](https://github.com/OpenSIPS/opensips-cp/assets/159455297/42ca2c1c-b941-43bf-b7f0-68cce09543df)

And unable to configure the dashboard (everything remains empty) : 
![image](https://github.com/OpenSIPS/opensips-cp/assets/159455297/4d23a438-11f8-415d-bec9-2722ee962f46)

Thanks

**Comment by bogdan-iancu** [comment]
guys, you are trying to use (via CP) some modules you do not have in OpenSIPS. Like @E2-Sterlin , do you have the `domain` module into your opensips ? And @Erwindae59 , do you have the `tracer` module set into your opensips?

You cannot use tools in CP without having the corresponding module loaded into your OpenSIPS cfg.
