### ISSUE TITLE
undefined function apc_store() in homer.php

### ISSUE THREAD

**Issue by Jeffrey2019** [OpenSIPS/opensips-cp#33]
Dear Sir/Madam
I am try to make integration between Homer and OpenSIPS Control Panel.
When I click homer link in control panel, there is an 500(Internal Server Error).
http://172.21.253.242/cp/tools/system/homer/homer.php

There is also error in log file: /var/log/apache2/error.log
What should I do to fix it?

`[Thu Jan 04 14:12:25.287841 2018] [:error] [pid 10616] [client 172.21.254.208:61842] PHP Fatal error:  Call to undefined function apc_store() in /var/www/opensips-cp/web/tools/system/homer/homer.php on line 50, referer: http://172.21.253.242/cp/menu.php`

**Comment by bogdan-iancu** [comment]
Hi @Jeffrey2019 , be sure you have php-apc package installed

**Comment by bogdan-iancu** [comment]
Added the APC php extension in the installation description.

**Comment by Jeffrey2019** [comment]
Dear Bogdan
After install php-apc package, the error disappeared.
But a new error on homer side.

`[Thu Jan 04 17:48:37.113790 2018] [:error] [pid 23028] [client 172.21.254.209:50662] PHP Fatal error:  Call to undefined function Authentication\\curl_init() in /var/www/html/homer/api/Authentication/External.php on line 71, referer: http://sip.opensips.org.cn/cp/tools/system/homer/homer.php`

php5-curl is not installed by homer quick installer scripts.

the fix is：
apt-get install php5-curl
 /etc/init.d/apache2 restart

Now, the integration is working perfect.
Thank you very much.
