### ISSUE TITLE
System > Mi Commands 

### ISSUE THREAD

**Issue by Jeffrey2019** [OpenSIPS/opensips-cp#34]
Dear Sir
OpenSIPS 2.3 + Control Panel 7.2.3(lastest commit)

When I click System > Mi Commands, there is error in /var/log/apache2/error.log
And mi commands is not populated in the drop down list, right to the eXecute button.

`[Thu Jan 04 23:17:40.798701 2018] [:error] [pid 18875] [client 172.21.254.209:51009] PHP Notice:  Undefined variable: box_val in /var/www/opensips-cp/web/tools/system/mi/lib/functions.inc.php on line 55, referer: http://172.21.253.242/cp/menu.php
[Thu Jan 04 23:17:40.798975 2018] [:error] [pid 18875] [client 172.21.254.209:51009] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/opensips-cp/config/session.inc.php on line 23, referer: http://172.21.253.242/cp/menu.php
[Thu Jan 04 23:17:40.799193 2018] [:error] [pid 18875] [client 172.21.254.209:51009] PHP Notice:  Undefined index: action in /var/www/opensips-cp/web/tools/system/mi/mi.php on line 58, referer: http://172.21.253.242/cp/menu.php
[Thu Jan 04 23:17:40.799235 2018] [:error] [pid 18875] [client 172.21.254.209:51009] PHP Notice:  Undefined index: action in /var/www/opensips-cp/web/tools/system/mi/mi.php on line 92, referer: http://172.21.253.242/cp/menu.php
[Thu Jan 04 23:17:40.799244 2018] [:error] [pid 18875] [client 172.21.254.209:51009] PHP Notice:  Undefined index: action in /var/www/opensips-cp/web/tools/system/mi/mi.php on line 99, referer: http://172.21.253.242/cp/menu.php`

Also, when I input 'which' command to execute, it also doesn't work.
`[Thu Jan 04 23:22:50.291084 2018] [:error] [pid 18877] [client 172.21.254.209:51069] PHP Notice:  Undefined variable: box_val in /var/www/opensips-cp/web/tools/system/mi/lib/functions.inc.php on line 55, referer: http://172.21.253.242/cp/tools/system/mi/mi.php
[Thu Jan 04 23:22:50.291318 2018] [:error] [pid 18877] [client 172.21.254.209:51069] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/opensips-cp/config/session.inc.php on line 23, referer: http://172.21.253.242/cp/tools/system/mi/mi.php
[Thu Jan 04 23:22:50.295352 2018] [:error] [pid 18877] [client 172.21.254.209:51069] PHP Notice:  Undefined variable: arguments in /var/www/opensips-cp/web/tools/system/mi/mi.php on line 72, referer: http://172.21.253.242/cp/tools/system/mi/mi.php`

I followed the instruction carefully with book and control panel website.
OpenSIPS 2.2 + Control Panel 6.2 works fine.

Thanks.

**Comment by bogdan-iancu** [comment]
Hi @Jeffrey2019 - I see you have only PHP Notices, no actual errors. The notices are harmless. Are you sure you properly configured the MI JSON connector back to OpenSIPS ?

**Comment by Jeffrey2019** [comment]
Dear Bogdan
After I add httpd.so and mi_json.so, and change from "fifo:/tmp/opensips_fifo" to httpd json in config file(config/boxes.global.inc.php), it works now.
Does that means OpenSIPS 2.3 + Control Panel 7.2.3 only support httpd json method?
If yes, the instructions in the book and control panel website need to be updated.

OpenSIPS 2.2 + Control Panel support fifo method.
Thanks.

`
loadmodule "httpd.so"
modparam("httpd", "port", 8080)
loadmodule "mi_json.so"`

**Comment by bogdan-iancu** [comment]
Hi @Jeffrey2019 , yes starting with OCP 7.2.3 only the JSON RPC backend will be supported for MI. This decision was taken based on the complexity of the data exchanged by OCP with Opensips, where FIFO and XML were not offering the best and efficient way to pack the data.
I checked the website http://controlpanel.opensips.org/ and the only place I found as not updated was for the MI tool (and had it updated). If you found any other places were the information was not updated, please let me know.

About the book - this covers OpenSIPS 2.1 with matches an older version of OCP 6.1.

**Comment by Jeffrey2019** [comment]
Dear @bogdan-iancu 
I think it is the book lead me to use file based fifo method. Nowhere else.
I suggest to remove "fifo:/tmp/opensips_fifo" in the boxes.global.inc.php file throughly, avoiding further confusion.

Thank you!

**Comment by bogdan-iancu** [comment]
The boxes file for 7.2.3 ( https://github.com/OpenSIPS/opensips-cp/blob/7.2.3/config/boxes.global.inc.php ) has no mentioning any more to any non JSON backends.

Thanks for reporting.

**Comment by Jeffrey2019** [comment]
Dear @bogdan-iancu 
Is it reasonable to change default ssl of monit to false as well,  in config/boxes.global.inc.php?
I don't know how to enable ssl on monit app.

Thanks.


`-$boxes[$box_id]['monit']['has_ssl']=1;
+$boxes[$box_id]['monit']['has_ssl']=0;`

**Comment by bogdan-iancu** [comment]
@Jeffrey2019, please open a separate feature request for this, and we will evaluate.

Anyhow, to have SSL in monit, in the httpd setting (in monitrc) add:

> SSL ENABLE
> PEMFILE  /etc/monit/file.pem

**Comment by shahidge4** [comment]
Dear @bogdan-iancu
there is an error when i click to reload on server
