### ISSUE TITLE
System > Statistics Monitor 7.2.3 issue

### ISSUE THREAD

**Issue by Jeffrey2019** [OpenSIPS/opensips-cp#35]
Dear Sir
OpenSIP 2.3 + Control Panel 7.2.3
When I click System > Statistics Monitor menu, the returned page is strange, compared with what I did in OpenSIPS 2.2 + Control panel 6.2

The error in the log file is as below:
`[Thu Jan 04 23:25:50.215032 2018] [:error] [pid 18886] [client 172.21.254.209:51128] PHP Warning:  Creating default object from empty value in /var/www/opensips-cp/config/db.inc.php on line 24, referer: http://172.21.253.242/cp/menu.php
[Thu Jan 04 23:25:50.263241 2018] [:error] [pid 18886] [client 172.21.254.209:51128] PHP Warning:  Creating default object from empty value in /var/www/opensips-cp/config/tools/system/smonitor/local.inc.php on line 25, referer: http://172.21.253.242/cp/menu.php
[Thu Jan 04 23:25:50.276682 2018] [:error] [pid 18886] [client 172.21.254.209:51128] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/opensips-cp/web/tools/system/smonitor/lib/put_select_boxes.php on line 25, referer: http://172.21.253.242/cp/menu.php
[Thu Jan 04 23:25:50.276781 2018] [:error] [pid 18886] [client 172.21.254.209:51128] PHP Notice:  Undefined variable: box_val in /var/www/opensips-cp/web/tools/system/smonitor/lib/functions.inc.php on line 198, referer: http://172.21.253.242/cp/menu.php
[Thu Jan 04 23:25:50.276910 2018] [:error] [pid 18886] [client 172.21.254.209:51128] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/opensips-cp/config/session.inc.php on line 23, referer: http://172.21.253.242/cp/menu.php
[Thu Jan 04 23:25:50.277013 2018] [:error] [pid 18886] [client 172.21.254.209:51128] PHP Notice:  Undefined index: var in /var/www/opensips-cp/web/tools/system/smonitor/rt_stats.php on line 44, referer: http://172.21.253.242/cp/menu.php
[Thu Jan 04 23:25:50.277032 2018] [:error] [pid 18886] [client 172.21.254.209:51128] PHP Notice:  Undefined index: module_id in /var/www/opensips-cp/web/tools/system/smonitor/rt_stats.php on line 64, referer: http://172.21.253.242/cp/menu.php
[Thu Jan 04 23:25:50.277042 2018] [:error] [pid 18886] [client 172.21.254.209:51128] PHP Notice:  Undefined index: modules_no in /var/www/opensips-cp/web/tools/system/smonitor/rt_stats.php on line 72, referer: http://172.21.253.242/cp/menu.php
[Thu Jan 04 23:25:50.277057 2018] [:error] [pid 18886] [client 172.21.254.209:51128] PHP Notice:  Undefined index: reset_stats in /var/www/opensips-cp/web/tools/system/smonitor/rt_stats.php on line 75, referer: http://172.21.253.242/cp/menu.php
[Thu Jan 04 23:25:50.277083 2018] [:error] [pid 18886] [client 172.21.254.209:51128] PHP Notice:  Undefined index: modules_no in /var/www/opensips-cp/web/tools/system/smonitor/template/rt_stats.main.php on line 32, referer: http://172.21.253.242/cp/menu.php`

Thanks.

**Comment by bogdan-iancu** [comment]
This may be related to #34, mainly not having the MI Json interface properly configured, so the control Panel is not able to communicate and fetch data from OpenSIPS

**Comment by Jeffrey2019** [comment]
Dear Bogdan
After I add httpd.so and mi_json.so, and change from "fifo:/tmp/opensips_fifo" to httpd json in config file(config/boxes.global.inc.php), it works now.

Thanks.
