### ISSUE TITLE
CDR Viewer error when search with TIME criteria

### ISSUE THREAD

**Issue by Jeffrey2019** [OpenSIPS/opensips-cp#36]
Dear Sir/Madam
In OCP 7.2.3 with OpenSIP 2.3, PostgreSQL.
System > CDR Viewer
The default CDR Viewer main page is OK.
When search with criteria, it will return below error message:
Failed to issue query, error message : MDB2 Error: unknown error

Thanks.

errors in /var/log/apache2/error.log:

`[Mon Jan 08 12:28:37.424892 2018] [:error] [pid 5333] [client 172.21.254.211:61045] PHP Warning:  Creating default object from empty value in /var/www/opensips-cp/config/tools/system/cdrviewer/local.inc.php on line 28, referer: http://172.21.253.242/cp/tools/system/cdrviewer/cdrviewer.php?action=search
[Mon Jan 08 12:28:37.441317 2018] [:error] [pid 5333] [client 172.21.254.211:61045] PHP Notice:  Undefined variable: show_all in /var/www/opensips-cp/web/tools/system/cdrviewer/cdrviewer.php on line 47, referer: http://172.21.253.242/cp/tools/system/cdrviewer/cdrviewer.php?action=search
[Mon Jan 08 12:28:37.441359 2018] [:error] [pid 5333] [client 172.21.254.211:61045] PHP Notice:  Undefined variable: search_regexp in /var/www/opensips-cp/web/tools/system/cdrviewer/cdrviewer.php on line 57, referer: http://172.21.253.242/cp/tools/system/cdrviewer/cdrviewer.php?action=search
[Mon Jan 08 12:28:37.441371 2018] [:error] [pid 5333] [client 172.21.254.211:61045] PHP Notice:  Undefined variable: cdr_field in /var/www/opensips-cp/web/tools/system/cdrviewer/cdrviewer.php on line 58, referer: http://172.21.253.242/cp/tools/system/cdrviewer/cdrviewer.php?action=search
[Mon Jan 08 12:28:37.441389 2018] [:error] [pid 5333] [client 172.21.254.211:61045] PHP Notice:  Undefined variable: export in /var/www/opensips-cp/web/tools/system/cdrviewer/cdrviewer.php on line 66, referer: http://172.21.253.242/cp/tools/system/cdrviewer/cdrviewer.php?action=search
[Mon Jan 08 12:28:37.441547 2018] [:error] [pid 5333] [client 172.21.254.211:61045] PHP Notice:  Undefined variable: sql_search in /var/www/opensips-cp/web/tools/system/cdrviewer/template/cdrviewer.main.php on line 71, referer: http://172.21.253.242/cp/tools/system/cdrviewer/cdrviewer.php?action=search
`

**Comment by bogdan-iancu** [comment]
Hi @Jeffrey2019 , not sure why, but I suspect there is (again) a postgres related issue :) . What is the criteria you are selecting ? Maybe the SQL query is not 100% postgres compliant - can you see (at progres level) the query sent by Control Panel ?

**Comment by Jeffrey2019** [comment]
@bogdan-iancu 

Absolutely right!!

select count(*) from acc where (1=1)  and unix_timestamp('2018-01-01 00:00:00')  <= unix_timestamp(time)



`2018-01-10 19:40:44 CST [21618-1] opensips@opensips LOG:  statement: SET SESSION DATESTYLE = 'ISO'
2018-01-10 19:40:44 CST [21618-2] opensips@opensips LOG:  statement: select count(*) from acc where (1=1)  and unix_timestamp('2018-01-01 00:00:00')  <= unix_timestamp(time)
2018-01-10 19:40:44 CST [21618-3] opensips@opensips ERROR:  function unix_timestamp(unknown) does not exist at character 43
2018-01-10 19:40:44 CST [21618-4] opensips@opensips HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2018-01-10 19:40:44 CST [21618-5] opensips@opensips STATEMENT:  select count(*) from acc where (1=1)  and unix_timestamp('2018-01-01 00:00:00')  <= unix_timestamp(time)`

**Comment by bogdan-iancu** [comment]
So, there is no unix_timestamp() on postgres....right ? :)

**Comment by Jeffrey2019** [comment]
@bogdan-iancu 
Yes, right!

**Comment by bogdan-iancu** [comment]
This is not an easy one as right now I see no way how to leverage this as the MDB level - basically how to make the query backend independent (as SQL does not provide a standard for the time manipulation functions)....

**Comment by Jeffrey2019** [comment]
@bogdan-iancu 
Let me provide a workaround before a better fix.



CREATE FUNCTION unix_timestamp(time_str varchar(19) ) RETURNS integer AS $$
SELECT (date_part('epoch',to_timestamp(time_str, 'YYYY-MM-DD HH24:MI:SS')))::integer; 
$$ LANGUAGE SQL IMMUTABLE;

CREATE FUNCTION unix_timestamp(time_str TIMESTAMP ) RETURNS integer AS $$
SELECT (date_part('epoch',time_str))::integer; 
$$ LANGUAGE SQL IMMUTABLE;

**Comment by bogdan-iancu** [comment]
Basically your suggestion is to to create this function when deploying the psotgres schema in  https://github.com/OpenSIPS/opensips-cp/blob/master/config/tools/admin/add_admin/ocp_admin_privileges.pgsql , which is mandatory for running OCP ?

**Comment by Jeffrey2019** [comment]
If no better solution, Yes.

**Comment by bogdan-iancu** [comment]
Thank you @Jeffrey2019 for the snapshot. Questions:
1) do we need to have both definitions ?
2) what you paste there, is the exact SQL code to insert into the .psql file ?

**Comment by Jeffrey2019** [comment]
@bogdan-iancu 
1. Yes, in case different type of input parameter provided.
2. Yes, exact SQL code I tested.

**Comment by bogdan-iancu** [comment]
Thank you @Jeffrey2019 for the info - is it too much if I ask you do a pull request for this change ? Just to be sure I don't insert any syntax mistake as postgres is one of my strong point.
If not, let me know I can do the change and you will validate it later.

**Comment by Jeffrey2019** [comment]
@bogdan-iancu 
Pull request created, with patch file attached.

**Comment by Jeffrey2019** [comment]
@bogdan-iancu 
Closed old pull request and created new pull request in correct way.

**Comment by bogdan-iancu** [comment]
Thank you @Jeffrey2019 , I merged #39 and #40 . If ok, please close this ticket.
