### ISSUE TITLE
Tables PostgreSQL

### ISSUE THREAD

**Issue by cleberb** [OpenSIPS/opensips-cp#45]
I can not find the file:

config/tools/admin/add_admin/ocp_admin_privileges.pgsql

Has postgresql support been removed?

**Comment by razvancrainea** [comment]
I've just restored the file in the new tool, `list_admin`. You can find the schema [there](https://github.com/OpenSIPS/opensips-cp/blob/master/config/tools/admin/list_admins/ocp_admin_privileges.pgsql).

The new CP will be using PDO, which supports postgres.
