### ISSUE TITLE
Suggestion to removing short tags

### ISSUE THREAD

**Issue by cleberb** [OpenSIPS/opensips-cp#47]
Here's one suggestion to removing short tags of the code, following the best practice recommendation in PHP7:

Shell commands used:

```
# cd /var/www/
# cp -a opensips-cp{,.bak}
# cd opensips-cp
# find . -iname '*.php' -type f -print0 | xargs -0 sed -i -e 's/<?$/<?php/g' -e 's/<? /<?php /g' -e '/<?php/! s/<?\([^=\"\ ]\)/<?php \1/g'
```

I performed a validation test with the command:

```
# cd /var/www
# git diff opensips-cp.bak opensips-cp
```

With this change, will no longer have to change the default behavior of the **`short_open_tag`** parameter in the **`php.ini`** file (value is **`Off`** in Debian Stretch).

In my test environment everything is functional, but I recommend evaluating it more deeply.

**Comment by razvancrainea** [comment]
Thanks for the detailed steps for this, really appreciate it!
If possible, can you make a pull request for this change? It would be nice to see exactly who contributed for this major change. If you need more info about doing a PR, you can follow [this](https://help.github.com/articles/about-pull-requests/) documentation.
