### ISSUE TITLE
drouting attr field problem. 

### ISSUE THREAD

**Issue by johandeclercqdemocon** [OpenSIPS/opensips-cp#49]
I use the latest version of opensips-cp. 
There seems to be a problem in the gui for attr in gateways of drouting. 
In the gui I can only type in 16 chars, where as the filed is defined as 254 chars. 
 
When I insert a long string in the db directly, then it is displayed correctly, however when I try to change the string and then save it. 
Opensips-cp gives a warning that I should shorten my string to 16 chars. I believe that you should be able use the full-length of the field.

**Comment by bogdan-iancu** [comment]
@johandeclercqdemocon , is this the trunk/master version of CP (for OpenSIPS 2.4) or the 7.2.3 CP version for OpenSIPS 2.3 ?

**Comment by johandeclercqdemocon** [comment]
Hello Bogdan, it’s 7.2.3

**Comment by bogdan-iancu** [comment]
The `attrs` field is limited to 128 char, not 16.
https://github.com/OpenSIPS/opensips-cp/blob/7.2.3/web/tools/system/drouting/template/gateways.add.php#L89

The only data limited to 16 chars is the length of the `PRI prefix` - https://github.com/OpenSIPS/opensips-cp/blob/7.2.3/web/tools/system/drouting/template/gateways.add.php#L54

**Comment by bogdan-iancu** [comment]
closing as there is no follow up here
