### ISSUE TITLE
Cannot edit admin users

### ISSUE THREAD

**Issue by smartvoxuk** [OpenSIPS/opensips-cp#50]
Add New Admin works as expected, so does delete, but editing an existing admin user does not work.
There is a message "- is already an existing admin -" on the screen when I click Save.

**Comment by bogdan-iancu** [comment]
@smartvoxuk , thanks for the report and please confirm the fix.

**Comment by smartvoxuk** [comment]
Have just tested and can confirm it is all working correctly now.
