### ISSUE TITLE
Admin access control not working

### ISSUE THREAD

**Issue by smartvoxuk** [OpenSIPS/opensips-cp#51]
Edit the access controls for an admin user and remove the tick from the "User Management" tool. Save.
Now login as the user and you are able to change the permissions back again even though you should not have permission to do so. This happens because the argument passed to get_priv() in index.php is "list_admins" and the checks done within the function attempt to match this tool name to the names already known and stored in an array of "tabs". There is no tab in that array with the name "list_admins" so the 'read_only' session variable does not get initialised. Modules then interpret the uninitialised session variable as meaning full access is permitted.

**Comment by bogdan-iancu** [comment]
thanks @smartvoxuk for the report - I did located the issue, working on a fix

**Comment by bogdan-iancu** [comment]
@smartvoxuk , an work around is available, I need to put more time into and evaluate the issue and the fix from the security perspective. I will keep the ticket open

**Comment by smartvoxuk** [comment]
Behaviour looks correct with the fix.
