### ISSUE TITLE
Timezone warning from login.php

### ISSUE THREAD

**Issue by smartvoxuk** [OpenSIPS/opensips-cp#52]
The http log file records a "PHP Warning" w.r.t. use of the date() function. The warning states that "you are *required* to use the date.timezone setting or the date_default_timezone_set() function". It then states that it will default to UTC. The report states that the infringement occurs at line 91 in /opensips-cp/web/login.php.

**Comment by bogdan-iancu** [comment]
@smartvoxuk , I think this issue is related to your installation - basically php is not able to detect the timezone on your machine.
See for example https://www.howtoforge.com/php-it-is-not-safe-to-rely-on-the-systems-timezone-settings

**Comment by smartvoxuk** [comment]
I changed the setting in php.ini as suggested and no longer get these warnings.
Please feel free to close this issue.
