### ISSUE TITLE
Can not  delete traces in Opensips-cp v8.2

### ISSUE THREAD

**Issue by zzz3z** [OpenSIPS/opensips-cp#55]
Hi Everyone,
Can't delete traces in Sip Trace by pressing "Delete Listed".
BR
Yuriy

**Comment by bogdan-iancu** [comment]
Thank you @zzz3z for your report. The fix is available, please confirm

**Comment by zzz3z** [comment]
Hello Bogdan,
Thank you very much. It works perfectly!
Best regards,
Yuriy
