### ISSUE TITLE
MI commands page proxy dropdown menu problem

### ISSUE THREAD

**Issue by calliotel** [OpenSIPS/opensips-cp#58]
Using the latest 8.2.4 (cloned today) I noticed that whatever sip prox I'm choosing in System -> MI Commands, always the first proxy will be chosen. So clocking to the dropdown switch in the top right of the screen won't do anything.
Here you can find the confoguration of the boxes
[boxes.txt](https://github.com/OpenSIPS/opensips-cp/files/2629230/boxes.txt)

**Comment by calliotel** [comment]
Hi Bogdan,

Do you need any more informations regarding this issue?

**Comment by bogdan-iancu** [comment]
Hey @calliotel , please check the 4a405f0b55f98d083b30f6e11cd8025ecd07870b commit, it should fix the problem

**Comment by calliotel** [comment]
Hi @bogdan-iancu,

Indeed the proxies are now apperaing in the dropdown list fine, I can select teh second one successfully. But even if I select the second proxy, all commands are executed against the first proxy, according to the history. I also didi a quick ngrep trace on port 8888 where opensips listens on, no traffic on the recond proxy, only on the first one.

**Comment by bogdan-iancu** [comment]
Please note that the history list is holding the MI runs for all the servers you have in the dropdown (the history is NOT per server).
I tested with 2 entries, one with a valid MI connector, another one with a faulty one ( generating "Failed to connect to 127.0.0.2 port 8090: Connection refused"). when changing the servers, I can see the error and also the updated list of available commands (in the lowed dropdown)

**Comment by calliotel** [comment]
@bogdan-iancu I think we talking about two different things.
Please try the following:

MI Commands page, choose the second defined SIP server in the dropdown list and select "uptime" in the another dropdown list and click "Execute". You will see that the uptime command is executed against the first SIP server regardless of that SIP server you choose in the dropdown menu. This is my problem.

**Comment by bogdan-iancu** [comment]
OK, I managed to reproduce that, investigating ....

**Comment by bogdan-iancu** [comment]
Managed to find the problem and the fix is now on git. Please confirm.

**Comment by calliotel** [comment]
I can confirm that it s working as expected.
