### ISSUE TITLE
PgSQL port connection

### ISSUE THREAD

**Issue by volga629** [OpenSIPS/opensips-cp#59]
Hello Everyone,
Installed latest version and tried connect to PgSQL database on custom port, but it connection failing.

Line in question 

````
if (!empty($config->db_port) ) $config->db_host = $config->db_host . ":" . $config->db_port;

````
Installed PHP

````
[root@aitossgui config]# rpm -qa | grep php
php-fedora-autoloader-1.0.0-2.fc27.noarch
php-pdo-7.1.23-1.fc27.x86_64
php-gd-7.1.23-1.fc27.x86_64
php-process-7.1.23-1.fc27.x86_64
php-pecl-apcu-bc-1.0.3-7.fc27.x86_64
php-pgsql-7.1.23-1.fc27.x86_64
php-json-7.1.23-1.fc27.x86_64
php-cli-7.1.23-1.fc27.x86_64
php-xml-7.1.23-1.fc27.x86_64
php-fpm-7.1.23-1.fc27.x86_64
php-pear-1.10.5-4.fc27.noarch
php-common-7.1.23-1.fc27.x86_64
php-7.1.23-1.fc27.x86_64
php-pecl-apcu-5.1.12-1.fc27.x86_64
````

````
Error!: SQLSTATE[08006] [7] could not translate host name "10.100.101.11:5235" to address: Name or service not known
````

**Comment by volga629** [comment]
After more testing look like port is not honored in any modules dsn connection to database. I adjusted db_connect.php 

```
$dsn = $config->db_driver . ':host=' . $config->db_host . ((!empty($config->db_port)) ? (';port=' . $config->db_port) : '') . ';dbname='. $config->db_name;
```
and commented out port definition with :  in ../config/db.inc.php

Right now I can login, but need fix all dsn for each module, not sure why it not use db_connect.php as centralized point.

Error in web ui

```
Error!: SQLSTATE[08006] [7] could not connect to server: No route to host Is the server running on host "10.100.101.11" and accepting TCP/IP connections on port 5432?

```

**Comment by bogdan-iancu** [comment]
Hi @volga629 , yes located the problem, it is related to the difference in how the port is handled in MDB2 and PDO - the PDO migration missed this aspect.
I will work in the next days on a fix

**Comment by bogdan-iancu** [comment]
@volga629 , please see the fixed I just pushed, if you could test and confirm.

**Comment by volga629** [comment]
Thank you for quick fix. I tested everything works as expected. Thank you again.
