### ISSUE TITLE
Update dispatcher and load_balancer tools for OpenSIPS 2.3

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips-cp#6]
With the addition of FreeSWITCH-flavoured weight calculations, both tools require an update either in order to support the newly added concepts (dispatcher + load_balancer) or simply ensure proper functioning / backwards-compatibility (dispatcher, where the `weight` column has changed from `INT` to `CHAR`).

**Comment by bogdan-iancu** [comment]
Done!
