### ISSUE TITLE
Impossible to send MI command

### ISSUE THREAD

**Issue by bduverger** [OpenSIPS/opensips-cp#67]
Ubuntu 18.04.2 LTS
OpenSIPS 2.4.6-1
opensips-cp branch master & 8.2.4

Hello,

When I try to send MI command, I have all the time this error:
**Unknwon/Unsupported type[] for MI URL <>**

I just change the line's port in boxes config:
`$boxes[$box_id]['mi']['conn']="json:127.0.0.1:8080/json";`

Everything else is by default and when I test OpenSIPS json, it's working.
curl "http://127.0.0.1:8080/json/uptime"
{"Now": "Mon Jul  8 11:43:45 2019", "Up since": "Mon Jul  8 11:36:04 2019", "Up time": "461 [sec]"}

In Apache2, I get this errors:
`[Mon Jul 08 11:47:18.964602 2019] [php7:notice] [pid 12082] [client 10.200.0.1:34978] PHP Notice:  session_start(): A session had already been started - ignoring in /var/www/opensips/config/session.inc.php on line 23, referer: http://sip04.prddmz.audiotel.com/cp/tools/system/mi/mi.php?action=execute
[Mon Jul 08 11:47:18.964950 2019] [php7:notice] [pid 12082] [client 10.200.0.1:34978] PHP Notice:  Undefined variable: box_val in /var/www/opensips/web/tools/system/mi/lib/functions.inc.php on line 55, referer: http://sip04.prddmz.audiotel.com/cp/tools/system/mi/mi.php?action=execute
[Mon Jul 08 11:47:18.965193 2019] [php7:warn] [pid 12082] [client 10.200.0.1:34978] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/opensips/web/tools/system/mi/lib/functions.inc.php on line 32, referer: http://sip04.prddmz.audiotel.com/cp/tools/system/mi/mi.php?action=execute`

Tested on Chrome/Firefox with OpenSIPs CP locally installed or on a different server, PHP 7.2 and PHP 5.

I found a quick fix

\-\-\- a/web/tools/system/mi/mi.php
\+\+\+ b/web/tools/system/mi/mi.php
@@ -47,7 +47,7 @@ if ($_GET['action']==\"execute\")
        $command=$_POST['mi_cmd'];
        if ($command=="") $error=true;
        if (!$error ) {
\-
\+               $current_box = "json:127.0.0.1:8080/json";
                $message=mi_command($command,$current_box,$errors,$status);
<p></p>
                $stupidtags = array("&lt;","&gt;");`

Thanks.

**Comment by bogdan-iancu** [comment]
The problem seems to be the missing box ID (this `$current_box`) - when accessing the MI tool, do you the dropdown (upper left corner) with the available boxes ?

**Comment by bduverger** [comment]
In the dropbox, I have only one occurence in list, **SIP server**, If I renamed it in **boxes.global.inc.php** I can see the new name but same error.

I created a new box, so under `$box_id=1;` I seted a new server and If I select it in dropbox, I can send MI command. If I select the first element in dropbox, I can also send MI commands.

So, it seems we need to select an element in the dropbox called **box_list** to initialize `$current_box`.

I think the change need to be done in the function `show_boxes` in **web/tools/system/mi/lib/functions.inc.php**

**Comment by bogdan-iancu** [comment]
Issue fixed by merging your #69 pull request, thank you
