### ISSUE TITLE
The web has notice information

### ISSUE THREAD

**Issue by ninuxer** [OpenSIPS/opensips-cp#68]
Hi，I installed OCP 8.2.4 according to official documents (http://controlpanel.opensips.org/htmldoc_8_2_4/INSTALL.html)
My Version Info：CentOS 6.5, php 7.0.14, nginx 1.11.2
But I see a lot of notice information on the web. like：
```
Notice: Undefined offset: 1 in /opt/htdocs/opensips-cp/web/tools/system/loadbalancer/template/loadbalancer.main.php on line 177
Notice: Undefined variable: lb_auto in /opt/htdocs/opensips-cp/web/tools/system/loadbalancer/template/loadbalancer.main.php on line 186
Notice: Undefined offset: 1 in /opt/htdocs/opensips-cp/web/tools/system/loadbalancer/template/loadbalancer.main.php on line 189
....
```
Is this caused by the php or nginx  is not installed properly?
PS:I tried xampp xampp 1.8.2、5.6.40, But I still had this kind of problem.

**Comment by bogdan-iancu** [comment]
@ninuxer , just ignore such notices, they are generated by some legacy php code (not friendly with initializing variables). But as behavior, it should be ok.

**Comment by ninuxer** [comment]
> @ninuxer , just ignore such notices, they are generated by some legacy php code (not friendly with initializing variables). But as behavior, it should be ok.

Get it，thanks a lot！
