### ISSUE TITLE
PHP Parse Error 2.2.3 (opensips) & 6.2 (CP)

### ISSUE THREAD

**Issue by gcasella** [OpenSIPS/opensips-cp#7]
Hi,

I get the following error messages in my apache log;

**Accessing User Management**
PHP Parse error:  syntax error, unexpected '}' in /var/www/opensips-cp/web/tools/users/user_management/template/user_management.main.php on line 272, referer: http://10.0.91.9/cp/menu.php

**Alias Management**
![image](https://cloud.githubusercontent.com/assets/7719536/23708359/a517e34e-03e3-11e7-8d3e-af77acb9c88d.png)

**ACL Management**
![image](https://cloud.githubusercontent.com/assets/7719536/23708394/bfc62b06-03e3-11e7-91f5-1954d329df33.png)

**List Admins**
PHP Parse error:  syntax error, unexpected '}' in /var/www/opensips-cp/web/tools/admin/list_admins/template/list_admins.main.php on line 150, referer: http://10.0.91.9/cp/menu.php

**RTPProxy**
PHP Parse error:  syntax error, unexpected '}' in /var/www/opensips-cp/web/tools/system/rtpproxy/template/rtpproxy.main.php on line 217, referer: http://10.0.91.9/cp/menu.php

**Comment by bogdan-iancu** [comment]
@gcasella , do you have the short_open_tag = On  option in your php.ini (for apache) ? see http://controlpanel.opensips.org/htmldoc/INSTALL.html

**Comment by gcasella** [comment]
Hi,


yes the short_open_tag option was set to "On" in my php.ini file.


________________________________

**Comment by razvancrainea** [comment]
@gcasella what is the PHP version you are using?

Did you modify anything in the source tree? If you checked it out using git, you can run `git status` to fiind out what is missing. Or it might be a typo in the config file.

Can you run the pages that opensips is complaining about in a php validator such as [this one](https://www.piliapp.com/php-syntax-check/)? Finally, can you attach a source file (taken from your browser?)

**Comment by bogdan-iancu** [comment]
Anything new @gcasella ? otherwise we will close this report as invalid
