### ISSUE TITLE
[Feature request] Please provide easier install options

### ISSUE THREAD

**Issue by paulvi** [OpenSIPS/opensips-cp#73]
Please provide easier install options,  
like docker or one install script.

http://controlpanel.opensips.org/htmldoc_8_X_X/INSTALL.html seems too long especially for those not familiar with PHP

**Comment by bogdan-iancu** [comment]
The Install doc gives all the needed info - if it can be wrapped up and simplified? yes, it can, but this requires time and effort. This is why we are glad to accept other people contributions. Right now all our work goes into the application itself.
