### ISSUE TITLE
Unable to link custom group to any Rule in Dynamic Routing Menu

### ISSUE THREAD

**Issue by SharadKumar97** [OpenSIPS/opensips-cp#74]
Hi, 

I am getting trouble assigning the group ID to the dr rules.  We can create any group but when we add rules in the dynamic routing menu, there is a drop-down to assign group ID. So by default, it shows only 2 groups to assign, 0 and 1. 

![image](https://user-images.githubusercontent.com/22173000/68161657-f3250400-ff1b-11e9-8d40-a64eb89afcd1.png)

Now if we try to assign that group to our new rule, we did not see anything.
![image](https://user-images.githubusercontent.com/22173000/68161728-1d76c180-ff1c-11e9-8dad-1da7855ffb78.png)

So right now, to assign custom group to rule, I manually change db entries in dr_rules table. Please try to solve this bug.

Thanks a lot.

**Comment by razvancrainea** [comment]
@SharadKumar97 you need to provision the groups in the `Settings` tag, under the `Group IDs File` field. Not sure why the `Groups` subtool allows you to set a Group that's not provisioned, perhaps there's a missing check there.
