### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by sdwru** [OpenSIPS/opensips-cp#77]
### Hardcoded directory dependency
In [your install guide](http://controlpanel.opensips.org/htmldoc_8_X_X/INSTALL.html), for Apache config you are using `/var/www/html/opensips-cp`, but we found a couple places in the code and scripts where you are using `/var/www/opensips-cp`.  For root directory, we are using `/var/www/opensips-cp` on Debian.  So all we needed to do was alter the directory in the Apache config.  Ideally, we should be able to put it wherever and name it whatever and not have to worry about hardcoded dependencies in the code or in scripts.

https://github.com/OpenSIPS/opensips-cp/search?q=var%2Fwww%2Fopensips-cp&unscoped_q=var%2Fwww%2Fopensips-cp

### Apache Config
Apache config for Apache v2.4 should use `Require all granted`, `Require all denied` instead of 
```
Order allow,deny
alow from all
```
and 
```
Order deny, allow
deny from all
```
I think the old way still works for Apache 2.4 but it's discouraged.  Any new installs would most likely be using an OS with Apache v2.4 these days.
https://httpd.apache.org/docs/2.4/upgrading.html

### PHP 7
Your instructions are referring to php 5 but any new installs will be using php 7.  We are using php 7.3 and so far it seems to work.  So if you install on Debian 9 the php directory will not be `/etc/php5`

**Comment by bogdan-iancu** [comment]
Thank you @sdwru , I pushed all the changes you suggested. If I missed something, please re-open.
