### ISSUE TITLE
can't load opensips-cp\web\tools\*\*\lib\*.main.js

### ISSUE THREAD

**Issue by AlexYe233** [OpenSIPS/opensips-cp#81]
Hi,I‘m using opensips-cp8.3.0 nginx1.16.1   and  PHP7.3-fpm PHP7.3.11-0(cli) on ubuntu0.19.10.2 
but opensips controlpanel  display as followings:
![1](https://user-images.githubusercontent.com/34712118/74587911-2b67d280-5033-11ea-9e79-00a30842a78a.PNG)
![2](https://user-images.githubusercontent.com/34712118/74587914-2efb5980-5033-11ea-845f-d0b29c4de9a1.PNG)
![3](https://user-images.githubusercontent.com/34712118/74587917-30c51d00-5033-11ea-8d41-aceb504c2821.PNG)
and there are errs in nginx'log like this:
 [error] 701#701: *477 FastCGI sent in stderr: "PHP message: PHP Warning:  require(lib/.main.js): failed to open stream: No such file or directory in /var/www/html/opensips-cp/web/tools/users/user_management/user_management.php on line 24PHP message: PHP Fatal error:  require(): Failed opening required 'lib/.main.js' (include_path='.:/usr/share/php') in /var/www/html/opensips-cp/web/tools/users/user_management/user_management.php on line 24" while reading response header from upstream, client: , server: , request: "GET /opensips-cp/web/tools/users/user_management/user_management.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "xxx", referrer: "https://xxx/opensips-cp/web/menu.php"
is there's any suggestions that helps solve the problem

**Comment by razvancrainea** [comment]
There seems to be a problem with the expansion of the `$_SERVER['PHP_SELF']` variable in php-fpm. Can you open the `template/header.php` file and replace `PHP_SELF` with `SCRIPT_NAME` on line 28?

**Comment by AlexYe233** [comment]
It works,thanks a lot
