### ISSUE TITLE
class PD0 not found

### ISSUE THREAD

**Issue by changzx** [OpenSIPS/opensips-cp#82]
![image](https://user-images.githubusercontent.com/42836671/80467470-6ad66780-8970-11ea-81d8-4c3cffc68039.png)

**Comment by bogdan-iancu** [comment]
That is PDO, the DB layer for PHP.
What operating system (and version) do you have ?

**Comment by changzx** [comment]
> That is PDO, the DB layer for PHP.
> What operating system (and version) do you have ?

centos7

**Comment by changzx** [comment]
？

**Comment by liviuchircu** [comment]
@changzx make sure you have PHP 7.  I think PDO should come with it, as I don't recall having to install something like `php7-pdo` :) I could be wrong though, haha

**Comment by changzx** [comment]
> @changzx make sure you have PHP 7. I think PDO should come with it, as I don't recall having to install something like `php7-pdo` :) I could be wrong though, haha

good, it's OK! haha
