### ISSUE TITLE
Replace json by mi in the box.inc.php

### ISSUE THREAD

**Issue by flaviogoncalves** [OpenSIPS/opensips-cp#87]
When using the master version and opensips 3.1, the file box.inc.

//  MI connector (via JSON backend):   json:host:port/json
$boxes[$box_id]['mi']['conn']="json:127.0.0.1:8888/json";

In 3.1 the default now is mi instead of json

//  MI connector (via JSON backend):   json:host:port/mi
$boxes[$box_id]['mi']['conn']="json:127.0.0.1:8888/mi";

Just to match configuration files generated by osipsconfig with the opensips control panel.

**Comment by bogdan-iancu** [comment]
This was fixed some time ago, thank you @flaviogoncalves
