### ISSUE TITLE
Error "Call to undefined method MDB2_Error::fetchAll()"

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips-cp#9]
Hello! Please consult this issue when you have a little time.
I see "HTTP ERROR 500" after enter the password, username and click "Login".
httpd logs:
```
[Thu Jun 22 07:43:20.095408 2017] [:error] [pid 27566] [client IP:52218] PHP Warning:  Creating default object from empty value in /var/www/opensips-cp/config/db.inc.php on line 24, referer: http://IP/cp/
[Thu Jun 22 07:43:20.131422 2017] [:error] [pid 27566] [client IP:52218] PHP Fatal error:  Call to undefined method MDB2_Error::fetchAll() in /var/www/opensips-cp/web/login.php on line 56, referer: http://IP/cp/
```
Warning in this code line:
```
    $config->db_driver = "pgsql";  
``` 
Error in this code line:
```
    $resultset1 = $result1->fetchAll(); 
```

SElinux disabled. opensips-cp 6.2.
Centos 7 version:
```
Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
I use this commands for install dependencies:
```
yum install php php-pear php-gd php-pgsql php-mbstring php-xml php-common php-curl php-gd php-ldap php-odbc php-pear php-xml php-xmlrpc php-mbstring php-snmp php-soap curl curl-devel
```
I use this commands for install pear:
```
pear install log
pear install MDB2
pear install MDB2#pgsql
```

Please help. Does not require an early solution.

**Comment by bogdan-iancu** [comment]
Hi @kertor , can you update from GIT and give it another try (check again the apache logs for errors). I pushed commit e3acf7f4ece330a6f01ca94ac877dbb7d79e464e for a correct error reporting.

**Comment by kertor** [comment]
Thanks Bogdan! Now i see that in browser after click to "Login":
```
Failed to issue query, error message : MDB2 Error: insufficient permissions
```
It`s strange, because db.inc.php have the same configuration with the opensipsctlrc(DB and tables creates successfull)... I will look for a problem on my side. Thanks)

**Comment by bogdan-iancu** [comment]
I backported the patch to trunk (future 6.3 for OpenSIPS 2.3) here a19abe7 .
For the moment I will close this, as it seems to be more a DB related issue, not CP related.
