### ISSUE TITLE
CDR Viewer

### ISSUE THREAD

**Issue by ShakedAmir** [OpenSIPS/opensips-cp#90]
CDR Viewer show with no style and filed selection
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function print_object(), 5 passed in /var/www/html/opensips-cp/web/tools/system/cdrviewer/lib/functions.inc.php on line 69 and exactly 7 expected

fixed with changing line 69 to 73:
print_object($obj_name."_month",1,12,$b,$disabled,true, ' onChange="changeState(\''.$obj_name.'\')"'); echo("<b>-</b>");
print_object($obj_name."_day",1,31,$a,$disabled,true, ' onChange="changeState(\''.$obj_name.'\')"'); echo("&nbsp;&nbsp;");
print_object($obj_name."_hour",0,23,$d,$disabled,true, ' onChange="changeState(\''.$obj_name.'\')"'); echo("<b>:</b>");
print_object($obj_name."_minute",0,59,$e,$disabled,true, ' onChange="changeState(\''.$obj_name.'\')"'); echo("<b>:</b>");
print_object($obj_name."_second",0,59,$f,$disabled,true, ' onChange="changeState(\''.$obj_name.'\')"');

**Comment by bogdan-iancu** [comment]
@ShakedAmir , thanks for the report, please see my commit 869d7d5 for the proper fix - could you confirm it ?
