### ISSUE TITLE
Number of parameters and tokens mismatch inserting a user

### ISSUE THREAD

**Issue by vbomfim** [OpenSIPS/opensips-cp#99]
**Version**: opensips-cp 8.3.2

**Error Message**:
PHP Warning:  PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in /var/www/html/opensips-cp/web/tools/users/user_management/user_management.php on line 287, referer: http://192.168.2.46/opensips-cp/web/tools/users/user_management/user_management.php?action=add

**How to reproduce**: User Management -> Add new user -> Fill the form -> Register

**Problem**: Number of parameters and tokens mismatch inserting a user

**Merge Request**: https://github.com/OpenSIPS/opensips-cp/pull/98

**Changes**:
File: /var/www/html/opensips-cp/web/tools/users/user_management/user_management.php
Line 274: replaced
$sql .= ') VALUES (?, ?, ?, ?, ? ';
with:
$sql .= ') VALUES (?, ?, ?, ? ';

**Comment by bogdan-iancu** [comment]
Closed via #98
